name: WPILib CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch.
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    branches: [ "**" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2022-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      uses: actions/checkout@v3
      with: {"**"}
      run: chmod +x gradlew

    - name: Formatting the code
      uses: actions/checkout@v3
      with: {"**"}
      run: ./gradlew spotlessApply

    # Runs a single command using the runners shell
    - name: Compile and run tests on robot code
      uses: actions/checkout@v3
      with: {"**"}
      run: ./gradlew spotlessCheck

    - name: Commit back to GitHub
      uses: actions/checkout@v3
      with: {"**"}
      if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'}}
      run: |   
        git config --global user.name "github-actiuons[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git add -A
        if ! git diff-index --quiet HEAD; then
          git commit -m "Formatting"
          git push -u origin ${GITHUB_REF}
        fi
